
camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      grpc-address: http://localhost:26500
      rest-address: http://localhost:8088
      prefer-rest-over-grpc: false
server:
  port: 8099